'use client';
import { useRef, useState } from 'react';
import { authFetch } from '../auth-fetch';
import { usePermissions } from '../permissions';
import { Panel, rupiah } from '../ui';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Draft = { mappingApproved: boolean; facts: { number:string; buyerTin:string; buyerName:string; taxObjectCode?:string; lines?:Array<{ productId:string;name:string;net:string;tax:string;vatRate:string }> } };
type Goods = { Opt:string; Code:string; Unit:string };
export default function CoretaxExportWorkspace({token,documents}:{token:string;documents:Array<{id:string;number:string}>}) {
  const {identity,canAll}=usePermissions(token);const allowed=Boolean(identity?.roles.some(r=>['SUPER_ADMIN','OWNER','FINANCE'].includes(r)) && canAll('tax.view','tax.manage','report.export'));
  const [documentId,setDocumentId]=useState('');const [contract,setContract]=useState('FAKTUR_PK_1_4');const [draft,setDraft]=useState<Draft|null>(null);
  const [mapping,setMapping]=useState({SellerTIN:'',SellerIDTKU:'',BuyerAdress:'',BuyerIDTKU:'',TaxInvoiceOpt:'Normal',TrxCode:'01',BuyerDocument:'TIN',BuyerCountry:'IND',IDPlaceOfBusinessActivityOfIncomeRecipient:'',TaxCertificate:'',TaxObjectCode:'',Document:'Invoice',GovTreasurerOpt:'No',SP2DNumber:''});
  const [goods,setGoods]=useState<Record<string,Goods>>({});const [job,setJob]=useState<{id:string;status:string}|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const operation=useRef<{hash:string;key:string}|null>(null);
  async function api<T>(path:string,body?:unknown):Promise<T> {const response=await authFetch(`${API}${path}`,token,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(Array.isArray(data.message)?data.message.join(', '):data.message??'Permintaan gagal.');return data;}
  function key(payload:unknown){const hash=JSON.stringify(payload);if(operation.current?.hash!==hash)operation.current={hash,key:crypto.randomUUID()};return operation.current.key;}
  async function inspect(){setBusy(true);setMessage('');setDraft(null);setJob(null);try {const data=await api<Draft>(`/accounting-core/tax-exports/documents/${documentId}/draft?contract=${contract}`);setDraft(data);setGoods(Object.fromEntries((data.facts.lines??[]).map(line=>[line.productId,{Opt:'A',Code:'',Unit:''}])));setMapping(value=>({...value,TaxObjectCode:data.facts.taxObjectCode??''}));}catch(e){setMessage(e instanceof Error?e.message:'Source belum lengkap.');}finally{setBusy(false);}}
  async function approve(){if(!draft||busy)return;setBusy(true);try{const legal=contract==='FAKTUR_PK_1_4'?{SellerTIN:mapping.SellerTIN,SellerIDTKU:mapping.SellerIDTKU,BuyerAdress:mapping.BuyerAdress,BuyerIDTKU:mapping.BuyerIDTKU,TaxInvoiceOpt:mapping.TaxInvoiceOpt,TrxCode:mapping.TrxCode,BuyerDocument:mapping.BuyerDocument,BuyerCountry:mapping.BuyerCountry,goods}:{SellerTIN:mapping.SellerTIN,SellerIDTKU:mapping.SellerIDTKU,IDPlaceOfBusinessActivityOfIncomeRecipient:mapping.IDPlaceOfBusinessActivityOfIncomeRecipient,TaxCertificate:mapping.TaxCertificate,TaxObjectCode:mapping.TaxObjectCode,Document:mapping.Document,GovTreasurerOpt:mapping.GovTreasurerOpt,SP2DNumber:mapping.SP2DNumber};const body={contract,mapping:legal};await api(`/accounting-core/tax-exports/documents/${documentId}/approve-mapping`,{...body,operationKey:key({documentId,...body})});operation.current=null;setDraft({...draft,mappingApproved:true});setMessage('Mapping legal disetujui dan menjadi snapshot. Nominal dan tarif tetap berasal dari Tax Core.');}catch(e){setMessage(e instanceof Error?e.message:'Mapping belum disetujui.');}finally{setBusy(false);}}
  async function enqueue(){setBusy(true);try{const body={contract,documentIds:[documentId]};setJob(await api('/accounting-core/tax-exports',{...body,operationKey:key(body)}));setMessage('XML masuk antrean worker. Periksa status, lalu unduh untuk review/import Coretax.');}catch(e){setMessage(e instanceof Error?e.message:'Export belum dibuat.');}finally{setBusy(false);}}
  async function status(){if(!job)return;try{const result=await api<{items:Array<{id:string;status:string}>}>('/reports/jobs?limit=100');const row=result.items.find(row=>row.id===job.id);if(row)setJob(row);else setMessage('Job belum terlihat pada halaman terakhir laporan. Periksa menu Export Jobs.');}catch(e){setMessage(e instanceof Error?e.message:'Status belum tersedia.');}}
  async function download(){if(!job)return;const response=await authFetch(`${API}/reports/jobs/${job.id}/download`,token);if(!response.ok){setMessage('Berkas belum tersedia atau sudah kedaluwarsa.');return;}const href=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=href;link.download=`${job.id}.xml`;link.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
  if(!allowed)return null;
  return <Panel eyebrow="CORETAX XML" title="Review dan export dokumen pajak" badge="Provider belum tersertifikasi">
    <p className="sectionHelp">Faktur PK v1.4 dan BPPU memakai kontrak berbeda. Review NPWP/NITKU, kode transaksi, barang/jasa, dan satuan sebelum menyetujui mapping. Import/penyerahan ke DJP perlu verifikasi operator dan penyedia produksi.</p>{message&&<p className="notice" role="status">{message}</p>}
    <div className="grid2"><label>Dokumen<select value={documentId} onChange={e=>{setDocumentId(e.target.value);setDraft(null);setJob(null);}}><option value="">Pilih dokumen ISSUED</option>{documents.map(row=><option key={row.id} value={row.id}>{row.number}</option>)}</select></label><label>Kontrak<select value={contract} onChange={e=>{setContract(e.target.value);setDraft(null);setJob(null);}}><option value="FAKTUR_PK_1_4">Faktur PK v1.4</option><option value="BPPU_2024_11">BPPU Unifikasi 2024-11</option></select></label></div><button className="secondary" type="button" disabled={!documentId||busy} onClick={()=>void inspect()}>Periksa source dan rekonsiliasi</button>
    {draft&&<><p>{draft.facts.number} · {draft.facts.buyerName} · NPWP {draft.facts.buyerTin}</p>{!draft.mappingApproved&&<><div className="grid2"><label>NPWP penjual (16 digit)<input inputMode="numeric" maxLength={16} value={mapping.SellerTIN} onChange={e=>setMapping({...mapping,SellerTIN:e.target.value})}/></label><label>NITKU penjual (22 digit)<input inputMode="numeric" maxLength={22} value={mapping.SellerIDTKU} onChange={e=>setMapping({...mapping,SellerIDTKU:e.target.value})}/></label>{contract==='FAKTUR_PK_1_4'?<><label>Kode transaksi<input maxLength={2} value={mapping.TrxCode} onChange={e=>setMapping({...mapping,TrxCode:e.target.value})}/></label><label>Alamat pembeli<textarea maxLength={500} value={mapping.BuyerAdress} onChange={e=>setMapping({...mapping,BuyerAdress:e.target.value})}/></label><label>NITKU pembeli (opsional)<input maxLength={22} value={mapping.BuyerIDTKU} onChange={e=>setMapping({...mapping,BuyerIDTKU:e.target.value})}/></label></>:<><label>NITKU penerima penghasilan<input maxLength={22} value={mapping.IDPlaceOfBusinessActivityOfIncomeRecipient} onChange={e=>setMapping({...mapping,IDPlaceOfBusinessActivityOfIncomeRecipient:e.target.value})}/></label><label>Kode objek dari Tax Core<input readOnly value={mapping.TaxObjectCode}/></label><label>Jenis dokumen<input maxLength={100} value={mapping.Document} onChange={e=>setMapping({...mapping,Document:e.target.value})}/></label><label>Sertifikat pajak (opsional)<input value={mapping.TaxCertificate} onChange={e=>setMapping({...mapping,TaxCertificate:e.target.value})}/></label></>}</div>{draft.facts.lines?.map((line,index)=><div className="sectionBlock" key={`${line.productId}-${index}`}><strong>{line.name}</strong><p>DPP {rupiah(Number(line.net))} · PPN {rupiah(Number(line.tax))} · Tarif statutory {Number(line.vatRate)}%</p><div className="grid2"><label>Barang / jasa<select value={goods[line.productId]?.Opt??'A'} onChange={e=>setGoods({...goods,[line.productId]:{...goods[line.productId],Opt:e.target.value}})}><option value="A">Barang</option><option value="B">Jasa</option></select></label><label>Kode barang/jasa DJP<input value={goods[line.productId]?.Code??''} onChange={e=>setGoods({...goods,[line.productId]:{...goods[line.productId],Code:e.target.value}})}/></label><label>Kode satuan DJP<input value={goods[line.productId]?.Unit??''} onChange={e=>setGoods({...goods,[line.productId]:{...goods[line.productId],Unit:e.target.value}})}/></label></div></div>)}<button type="button" disabled={busy} onClick={()=>void approve()}>Setujui mapping legal</button></>}{draft.mappingApproved&&<button type="button" disabled={busy||Boolean(job)} onClick={()=>void enqueue()}>Buat export XML</button>}</>}
    {job&&<div className="actionRow"><strong>Job {job.status}</strong><button type="button" className="secondary" onClick={()=>void status()}>Periksa status XML</button>{job.status==='DONE'&&<button type="button" onClick={()=>void download()}>Unduh XML aman</button>}{['RETRY','DEAD_LETTER'].includes(job.status)&&<small>Periksa worker dan mapping sebelum memulai export baru. Tidak ada penyerahan pajak otomatis.</small>}</div>}
  </Panel>;
}
