'use client';
import { FormEvent, useEffect, useState } from 'react';
import { durableOperation } from '../../../../packages/contracts/src/ppob-operation';
import { authFetch } from '../auth-fetch';
import { usePermissions } from '../permissions';
import { Panel, Table } from '../ui';
type Draft={id:string;status:string;warehouseId:string;opnameId:string|null;employeeId?:string;lines:Array<{key:string;quantity:number;unit:string|null}>};
type Opname={id:string;number:string;warehouseId:string;locationId?:string|null;status:string};
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
export default function MobileStockCount({token}:{token:string}){
  const {canAll,identity}=usePermissions(token);const allowed=canAll('inventory.opname');
  const [opnames,setOpnames]=useState<Opname[]>([]);const [opnameId,setOpnameId]=useState('');
  const [draft,setDraft]=useState<Draft|null>(null);const [codeKind,setCodeKind]=useState<'barcode'|'sku'>('barcode');const [barcode,setBarcode]=useState('');const [quantity,setQuantity]=useState(1);const [reason,setReason]=useState('');
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const selected=opnames.find(row=>row.id===opnameId);const slot=`toko360_mobile_scan:${identity?.sub}:${draft?.id}`;
  async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await authFetch(`${API}${path}`,token,{...init,headers:{'Content-Type':'application/json',...init?.headers}});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.message??`HTTP ${response.status}`),{status:response.status});return data;}
  async function run(action:()=>Promise<void>){if(!allowed||busy)return;setBusy(true);setMessage('');try{await action();}catch(error){setMessage(error instanceof Error?error.message:'Hitungan belum dapat diproses.');}finally{setBusy(false);}}
  useEffect(()=>{if(!allowed)return;void api<Opname[]|{items:Opname[]}>('/advanced-inventory/stock-opnames').then(page=>setOpnames((Array.isArray(page)?page:page.items).filter(row=>['DRAFT','COUNTING'].includes(row.status)))).catch(error=>setMessage(error instanceof Error?error.message:'Stock opname gagal dimuat.'));},[token,allowed]);
  async function open(event:FormEvent){event.preventDefault();await run(async()=>{if(!selected)return;const deviceSlot=`toko360_mobile_device:${identity?.sub}`;let deviceId=localStorage.getItem(deviceSlot);if(!deviceId){deviceId=`web-count:${crypto.randomUUID()}`;localStorage.setItem(deviceSlot,deviceId);}const row=await api<{id:string}>('/mobile-ops/drafts/open',{method:'POST',body:JSON.stringify({deviceId,warehouseId:selected.warehouseId,opnameId:selected.id,...(selected.locationId?{locationId:selected.locationId}:{})})});setDraft(await api(`/mobile-ops/drafts/${row.id}`));setMessage('Draft dibuka. Scan hanya merekam hitungan; stok belum berubah.');});}
  async function scan(event:FormEvent){event.preventDefault();await run(async()=>{if(!draft||draft.status!=='OPEN')return;const payload={...(codeKind==='sku'?{sku:barcode.trim()}:{barcode:barcode.trim()}),quantity};const operationKey=await durableOperation(sessionStorage,slot,payload,'mobile-scan');try{await api(`/mobile-ops/drafts/${draft.id}/scan`,{method:'POST',body:JSON.stringify({...payload,operationKey})});sessionStorage.removeItem(slot);setBarcode('');setQuantity(1);setDraft(await api(`/mobile-ops/drafts/${draft.id}`));setMessage('Scan tersimpan.');}catch(error){if([400,403,404,422].includes((error as {status:number}).status))sessionStorage.removeItem(slot);throw error;}});}
  if(!allowed)return null;
  return <Panel eyebrow="MOBILE STOCK COUNT" title="Scan hitungan gudang">
    <p className="sectionHelp">Pilih stock opname kanonik pada cabang aktif. Scan berulang karena retry memakai operation key yang sama. Setelah draft dikirim, supervisor tetap meninjau, menyetujui, dan memposting melalui Stock Opname.</p>
    <form className="formStack" onSubmit={open}><label>Stock opname<select required value={opnameId} disabled={busy||draft?.status==='OPEN'} onChange={e=>setOpnameId(e.target.value)}><option value="">Pilih sesi DRAFT / COUNTING</option>{opnames.map(row=><option key={row.id} value={row.id}>{row.number} · {row.status}</option>)}</select></label><button disabled={busy||!selected}>Buka / lanjutkan draft perangkat</button></form>
    {draft&&<><p>Draft {draft.id} · {draft.status}</p><form className="formStack" onSubmit={scan}><label>Jenis kode<select value={codeKind} disabled={busy||draft.status!=='OPEN'} onChange={e=>{setCodeKind(e.target.value as 'barcode'|'sku');setBarcode('');}}><option value="barcode">Barcode</option><option value="sku">SKU</option></select></label><label>{codeKind==='sku'?'SKU':'Barcode'}<input required maxLength={160} value={barcode} disabled={busy||draft.status!=='OPEN'} onChange={e=>setBarcode(e.target.value)} autoComplete="off"/></label><label>Jumlah fisik<input required type="number" min={1} step={1} disabled={busy||draft.status!=='OPEN'} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><button disabled={busy||draft.status!=='OPEN'||!barcode.trim()}>Simpan scan</button></form><Table head={['Barcode / SKU','Jumlah','Satuan']} rows={draft.lines.map(row=>[row.key,row.quantity,row.unit??'base unit'])} empty="Belum ada scan."/>
    {draft.status==='OPEN'&&<div className="formStack"><button type="button" disabled={busy||!draft.opnameId||!draft.lines.length} onClick={()=>void run(async()=>{await api(`/mobile-ops/drafts/${draft.id}/submit`,{method:'POST',body:JSON.stringify({opnameId:draft.opnameId})});sessionStorage.removeItem(slot);setDraft(await api(`/mobile-ops/drafts/${draft.id}`));setMessage('Hitungan masuk Stock Opname. Lanjutkan review dan approval kanonik.');})}>Kirim hitungan ke Stock Opname</button><label>Alasan membuang draft<input minLength={3} maxLength={400} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" className="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run(async()=>{await api(`/mobile-ops/drafts/${draft.id}/discard`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});sessionStorage.removeItem(slot);setDraft(await api(`/mobile-ops/drafts/${draft.id}`));setMessage('Draft dibuang dengan alasan tercatat.');})}>Buang draft dengan alasan</button></div>}</>}
    {message&&<p className="notice" role="status">{message}</p>}
  </Panel>;
}
