'use client';
import { useEffect, useRef, useState } from 'react';
type Api = <T>(path: string, init?: RequestInit) => Promise<T>;
type Order = { id: string; number: string; status: string; total: string | number };
const money = (amount: number) => new Intl.NumberFormat('id-ID',{ style:'currency', currency:'IDR',maximumFractionDigits:0 }).format(amount);
function useOperation() { const ref = useRef<{ hash: string; key: string } | null>(null); return { key(payload: unknown) { const hash = JSON.stringify(payload); if (ref.current?.hash !== hash) ref.current = { hash, key: crypto.randomUUID() }; return ref.current.key; }, done() { ref.current = null; } }; }
export function retailPermission(token: string, roles: string[], permissions: string[]) { try { const claims = JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))); return Array.isArray(claims.roles) && claims.roles.some((r: string) => roles.includes(r)) && (claims.roles.includes('SUPER_ADMIN') || permissions.every(p => claims.permissions?.includes(p))); } catch { return false; } }

export function ShipLaterPanel({ api, warehouseId, customerId, cashierShiftId, items, cashTenders, onComplete, onReserved }: { api: Api; warehouseId: string; customerId: string; cashierShiftId: string; items: Array<{ productId: string; quantity: number; variantId?: string; productUnitId?: string; barcodeCode?: string }>; cashTenders: Array<{ code: string; name: string }>; onComplete: () => Promise<void>; onReserved: (reserved:boolean) => void }) {
  const [fulfillmentType, setType] = useState('PICKUP'); const [address, setAddress] = useState(''); const [order, setOrder] = useState<Order | null>(null);
  const [tenderCode, setTenderCode] = useState(cashTenders[0]?.code ?? ''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const createOperation = useOperation(); const cashOperation = useOperation();
  const [pending, setPending] = useState<Order[]>([]); const [cursor,setCursor] = useState<string|null>(null);
  async function recover(next?:string) { try { const page = await api<{items:Order[];pageInfo:{nextCursor:string|null}}>(`/orders/staff?limit=20${next ? `&cursor=${encodeURIComponent(next)}` : ''}`);setPending(rows=>next?[...rows,...page.items]:page.items);setCursor(page.pageInfo.nextCursor); } catch(e) {setMessage(e instanceof Error?e.message:'Pesanan tertunda belum dapat dimuat.');} }
  useEffect(()=>{void recover();},[]);
  async function cancel() {if (!order || busy) return;setBusy(true);try {await api(`/orders/${order.id}/staff-cancel`,{method:'POST',body:JSON.stringify({reason:'Dibatalkan operator sebelum menerima pembayaran'})});setOrder(null);onReserved(false);createOperation.done();cashOperation.done();await recover();setMessage('Pesanan dibatalkan dan reservasi stok dilepas.');} catch(e) {setMessage(e instanceof Error?e.message:'Pembatalan gagal.');} finally {setBusy(false);} }

  async function create() { if (busy) return; setBusy(true); try { const body = { warehouseId, customerId, cashierShiftId, items, fulfillmentType, ...(address.trim() ? { address: address.trim() } : {}) }; setOrder(await api<Order>('/orders/staff', { method:'POST', body:JSON.stringify({ ...body, operationKey:createOperation.key(body) }) })); onReserved(true); setMessage('Stok direservasi. Cocokkan total server sebelum menerima pembayaran kas.'); } catch(e) { setMessage(e instanceof Error ? e.message : 'Order belum tersimpan.'); } finally { setBusy(false); } }
  async function pay() { if (!order || busy) return; setBusy(true); try { const body = { expectedAmount:Number(order.total),tenderCode }; const paid = await api<Order>(`/orders/${order.id}/staff-cash`, { method:'POST', body:JSON.stringify({ ...body, operationKey:cashOperation.key({ id:order.id,...body }) }) }); setOrder(paid); createOperation.done(); cashOperation.done(); onReserved(false); await onComplete(); setMessage(`${paid.number} dibayar. Lanjutkan inspeksi dan pemenuhan di menu Pesanan/Pengiriman Admin.`); } catch(e) { setMessage(e instanceof Error ? e.message : 'Pembayaran belum terkonfirmasi. Ulangi dengan order yang sama.'); } finally { setBusy(false); } }
  return <details className="returnPanel"><summary>KIRIM / AMBIL BELAKANGAN</summary><div className="returnWorkspace"><p className="panelNote">Pelanggan dan shift aktif wajib dipilih. Total termasuk ongkir dari konfigurasi toko. Diskon/poin pada keranjang kasir tidak diterapkan pada jalur pesanan ini.</p>{message && <p role="status">{message}</p>}{!order && pending.length>0 && <><label>Pesanan tertunda<select value="" onChange={e=>{const row=pending.find(r=>r.id===e.target.value);if(row){setOrder(row);onReserved(true);}}}><option value="">Pilih untuk melanjutkan / membatalkan</option>{pending.map(row=><option key={row.id} value={row.id}>{row.number} · {money(Number(row.total))}</option>)}</select></label>{cursor && <button type="button" className="secondary" onClick={()=>void recover(cursor)}>Pesanan berikutnya</button>}</>}{!order ? <><label>Pemenuhan<select value={fulfillmentType} onChange={e => setType(e.target.value)}><option value="PICKUP">Ambil di toko nanti</option><option value="DELIVERY">Kirim dari toko</option></select></label>{fulfillmentType === 'DELIVERY' && <label>Alamat pengiriman<textarea maxLength={500} value={address} onChange={e => setAddress(e.target.value)} /></label>}<button type="button" disabled={busy || !items.length || !warehouseId || !customerId || !cashierShiftId} onClick={() => void create()}>Buat pesanan dan periksa total</button></> : <><strong>{order.number} · {money(Number(order.total))} · {order.status}</strong>{order.status === 'PAID' && <button type="button" className="secondary" onClick={()=>{setOrder(null);void recover();}}>Pesanan berikutnya</button>}{order.status !== 'PAID' && <><label>Tender kas<select required value={tenderCode} onChange={e => setTenderCode(e.target.value)}><option value="">Pilih kas</option>{cashTenders.map(t => <option key={t.code} value={t.code}>{t.name}</option>)}</select></label><button type="button" disabled={busy || !tenderCode} onClick={() => void pay()}>Terima kas {money(Number(order.total))}</button><button type="button" className="secondary" disabled={busy} onClick={()=>void cancel()}>Batalkan sebelum dibayar</button></>}</>}</div></details>;
}

export function RetailExchangePanel({ api, returns, products, warehouseId, cashierShiftId, onComplete }: { api: Api; returns: Array<{ id: string; number: string; status: string; refundAmount: string | number }>; products: Array<{ id: string; name: string; retailAvailabilityError?: string | null }>; warehouseId: string; cashierShiftId: string; onComplete: () => Promise<void> }) {
  const [returnId, setReturnId] = useState(''); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState(1);
  const [difference, setDifference] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const operation = useOperation();
  const selected = returns.find(row => row.id === returnId);
  async function quote() { setBusy(true); try { const result = await api<{ total: string | number }>('/sales/quote', { method:'POST',body:JSON.stringify({ warehouseId,items:[{productId,quantity}] }) }); setDifference(Number(result.total) - Number(selected?.refundAmount ?? 0)); } catch(e) { setMessage(e instanceof Error ? e.message : 'Quote belum tersedia.'); } finally { setBusy(false); } }
  async function submit() { if (busy || difference === null) return; setBusy(true); try { const body = { saleReturnId:returnId,cashierShiftId,expectedDifference:difference,replacement:{ warehouseId,paymentMethod:'CASH',items:[{productId,quantity}] },confirmation:{} }; const result = await api<{ difference: string | number }>('/returns/exchanges', { method:'POST',body:JSON.stringify({ ...body,operationKey:operation.key(body) }) }); operation.done(); setDifference(null); setMessage(`Tukar barang selesai. Selisih kas ${money(Number(result.difference))}.`); await onComplete(); } catch(e) { setMessage(e instanceof Error ? e.message : 'Tukar barang belum diposting.'); } finally { setBusy(false); } }
  return <details className="returnPanel"><summary>TUKAR BARANG LANGSUNG</summary><div className="returnWorkspace"><p className="panelNote">Gunakan retur tunai yang inspeksinya sudah lulus. Retur dan penjualan pengganti diposting bersama; selisih diterima atau dikembalikan melalui kas shift ini.</p>{message && <p role="status">{message}</p>}<label>Retur asal<select value={returnId} onChange={e => { setReturnId(e.target.value); setDifference(null); }}><option value="">Pilih retur</option>{returns.filter(r => ['REQUESTED','APPROVED'].includes(r.status)).map(r => <option key={r.id} value={r.id}>{r.number} · {money(Number(r.refundAmount))}</option>)}</select></label><label>Barang pengganti<select value={productId} onChange={e => { setProductId(e.target.value); setDifference(null); }}><option value="">Pilih produk</option>{products.filter(p => !p.retailAvailabilityError).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Jumlah base unit<input type="number" min="1" step="1" value={quantity} onChange={e => { setQuantity(Math.max(1,Math.floor(Number(e.target.value)||1))); setDifference(null); }} /></label><button type="button" disabled={busy || !selected || !productId || !warehouseId || !cashierShiftId} onClick={() => void quote()}>Hitung selisih server</button>{difference !== null && <><strong>{difference >= 0 ? 'Terima kas' : 'Kembalikan kas'} {money(Math.abs(difference))}</strong><button type="button" disabled={busy} onClick={() => void submit()}>Konfirmasi tukar dan selisih kas</button></>}</div></details>;
}

export function ReceiptDeliveryControls({api,saleId}:{api:Api;saleId:string}) {
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const operation=useOperation();
  async function send(channel:'EMAIL'|'WHATSAPP') {if(busy)return;setBusy(true);try {const body={channel};await api(`/sales/${encodeURIComponent(saleId)}/deliver-receipt`,{method:'POST',body:JSON.stringify({...body,operationKey:operation.key({saleId,...body})})});operation.done();setMessage('Struk masuk antrean pengiriman ke akun pelanggan terverifikasi.');} catch(e) {setMessage(e instanceof Error?e.message:'Struk belum dapat dikirim.');} finally {setBusy(false);} }
  return <span className="rowActions"><button type="button" className="secondary" disabled={busy} onClick={()=>void send('EMAIL')}>Email struk</button><button type="button" className="secondary" disabled={busy} onClick={()=>void send('WHATSAPP')}>WhatsApp struk</button>{message&&<small role="status">{message}</small>}</span>;
}
