'use client';
import { useEffect, useRef, useState } from 'react';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Preferences = { marketingEmail: boolean; marketingWhatsapp: boolean; receiptEmail: boolean; receiptWhatsapp: boolean };
type Receipt = { id: string; number: string; total: string | number; createdAt: string };
export default function CustomerCommunications({ branchCode, token, emailVerified, phoneVerified }: { branchCode: string; token: string; emailVerified: boolean; phoneVerified: boolean }) {
  const [preferences, setPreferences] = useState<Preferences | null>(null); const [receipts, setReceipts] = useState<Receipt[]>([]); const [cursor, setCursor] = useState<string | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const operation = useRef<{ hash: string; key: string } | null>(null);
  async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`${API}/storefront/account${path}`, { method, cache: 'no-store', headers: { 'Content-Type': 'application/json', 'x-branch-code': branchCode, 'x-customer-session': token }, ...(body ? { body: JSON.stringify(body) } : {}) }); const data = await response.json(); if (!response.ok) throw new Error(Array.isArray(data.message) ? data.message.join(', ') : data.message ?? 'Permintaan gagal.'); return data; }
  async function loadReceipts(next?: string) { const page = await api<{ items: Receipt[]; pageInfo: { nextCursor: string | null } }>(`/receipts?limit=20${next ? `&cursor=${encodeURIComponent(next)}` : ''}`); setReceipts(prior => next ? [...prior, ...page.items] : page.items); setCursor(page.pageInfo.nextCursor); }
  useEffect(() => { void Promise.all([api<Preferences>('/communication-preferences').then(data => setPreferences({ marketingEmail:data.marketingEmail,marketingWhatsapp:data.marketingWhatsapp,receiptEmail:data.receiptEmail,receiptWhatsapp:data.receiptWhatsapp })),loadReceipts()]).catch(e => setMessage(e.message)); }, [branchCode, token, emailVerified, phoneVerified]);
  async function save(e: React.FormEvent) { e.preventDefault(); if (!preferences || busy) return; setBusy(true); const hash = JSON.stringify(preferences); if (operation.current?.hash !== hash) operation.current = { hash, key: crypto.randomUUID() }; try { const updated = await api<Preferences>('/communication-preferences', 'PATCH', { ...preferences, operationKey: operation.current.key }); setPreferences({ marketingEmail:updated.marketingEmail,marketingWhatsapp:updated.marketingWhatsapp,receiptEmail:updated.receiptEmail,receiptWhatsapp:updated.receiptWhatsapp }); operation.current = null; setMessage('Pilihan komunikasi tersimpan. Anda dapat mencabut persetujuan kapan saja.'); } catch(e) { setMessage(e instanceof Error ? e.message : 'Pilihan belum tersimpan.'); } finally { setBusy(false); } }
  async function openReceipt(row: Receipt) { const tab = window.open('about:blank', '_blank'); if (tab) tab.opener = null; try { const link = await api<{ path: string }>(`/receipts/${encodeURIComponent(row.number)}/link`); if (!tab) throw new Error('Izinkan popup, lalu buka struk kembali.'); tab.location.replace(`${API}${link.path}`); } catch(e) { tab?.close(); setMessage(e instanceof Error ? e.message : 'Struk belum tersedia.'); } }
  const labels: Array<[keyof Preferences,string,boolean]> = [['marketingEmail','Promo melalui email',emailVerified],['marketingWhatsapp','Promo melalui WhatsApp',phoneVerified],['receiptEmail','Pemberitahuan struk melalui email',emailVerified],['receiptWhatsapp','Pemberitahuan struk melalui WhatsApp',phoneVerified]];
  return <section className="customerCommunications" aria-label="Komunikasi dan struk pelanggan"><h3>Pilihan komunikasi</h3><p>Promo dan pemberitahuan struk memiliki persetujuan terpisah. Verifikasi kontak sebelum mengaktifkan pengiriman.</p>{message && <p role="status">{message}</p>}{preferences && <form onSubmit={save}>{labels.map(([key,label,verified]) => <label key={key}><input type="checkbox" checked={preferences[key]} disabled={!verified && !preferences[key]} onChange={e => setPreferences({ ...preferences, [key]: e.target.checked })} />{label}{!verified && ' · perlu verifikasi'}</label>)}<button type="submit" className="secondary" disabled={busy}>Simpan pilihan komunikasi</button></form>}<h3>Struk pembelian di toko</h3>{receipts.length ? receipts.map(row => <p key={row.id}><strong>{row.number}</strong> · {new Intl.NumberFormat('id-ID',{ style:'currency', currency:'IDR' }).format(Number(row.total))} <button className="secondary" type="button" onClick={() => void openReceipt(row)}>Buka struk</button></p>) : <p>Belum ada struk pada akun ini.</p>}{cursor && <button type="button" className="secondary" onClick={() => void loadReceipts(cursor).catch(e => setMessage(e.message))}>Struk berikutnya</button>}</section>;
}
